import React from 'react';
import withModalManager from '../../src/withModalManager';

const TestContainer = () => (
  <div>Hello World</div>
);

describe('withModalManager', () => {
  it('should render the component generated by withModalManager', () => {
    const TestComponent = withModalManager(TestContainer);

    expect(TestComponent.WrappedComponent).toBe(TestContainer);

    const result = mount(<TestComponent />);
    expect(result).toMatchSnapshot();
  });
});
