/* This file is auto-generated by terra-dev-site's generate-component-config config. */

// Component Examples
import TerraAggregatorIndex from './packages/terra-aggregator/examples/Index.site-page';
import TerraAppDelegateIndex from './packages/terra-app-delegate/examples/Index.site-page';
import TerraApplicationHeaderLayoutIndex from './packages/terra-application-header-layout/examples/Index.site-page';
import TerraApplicationLayoutAbout from './packages/terra-application-layout/examples/About.site-page';
import TerraApplicationLayoutExample from './packages/terra-application-layout/examples/Example.site-page';
import TerraApplicationLayoutUtils from './packages/terra-application-layout/examples/Utils.site-page';
import TerraApplicationLinksIndex from './packages/terra-application-links/examples/Index.site-page';
import TerraApplicationMenuLayoutIndex from './packages/terra-application-menu-layout/examples/Index.site-page';
import TerraApplicationNameIndex from './packages/terra-application-name/examples/Index.site-page';
import TerraApplicationUtilityIndex from './packages/terra-application-utility/examples/Index.site-page';
import TerraDisclosureManagerIndex from './packages/terra-disclosure-manager/examples/Index.site-page';
import TerraHookshotIndex from './packages/terra-hookshot/examples/Index.site-page';
import TerraInfiniteListIndex from './packages/terra-infinite-list/examples/Index.site-page';
import TerraLayoutIndex from './packages/terra-layout/examples/Index.site-page';
import TerraModalManagerIndex from './packages/terra-modal-manager/examples/Index.site-page';
import TerraNavigationLayoutIndex from './packages/terra-navigation-layout/examples/Index.site-page';
import TerraNavigationSideMenuIndex from './packages/terra-navigation-side-menu/examples/Index.site-page';
import TerraPopupIndex from './packages/terra-popup/examples/Index.site-page';
import TerraSlidePanelManagerIndex from './packages/terra-slide-panel-manager/examples/Index.site-page';
import TerraSlidePanelIndex from './packages/terra-slide-panel/examples/Index.site-page';
import TerraThemeProviderIndex from './packages/terra-theme-provider/examples/Index.site-page';

// Component Test Examples
import AggregatorStandalone from './packages/terra-aggregator/examples/test-examples/AggregatorStandalone.example';
import AggregatorWithDisclosure from './packages/terra-aggregator/examples/test-examples/AggregatorWithDisclosure.example';
import ApplicationHeaderDefault from './packages/terra-application-header-layout/examples/test-examples/ApplicationHeaderDefault.example';
import ApplicationLayout from './packages/terra-application-layout/examples/test-examples/ApplicationLayout.example';
import ApplicationLayoutEmpty from './packages/terra-application-layout/examples/test-examples/ApplicationLayoutEmpty.example';
import ApplicationLayoutHeader from './packages/terra-application-layout/examples/test-examples/ApplicationLayoutHeader.example';
import ApplicationLayoutHeaderSmall from './packages/terra-application-layout/examples/test-examples/ApplicationLayoutHeaderSmall.example';
import ApplicationLayoutMenu from './packages/terra-application-layout/examples/test-examples/ApplicationLayoutMenu.example';
import ApplicationLayoutNoTopNav from './packages/terra-application-layout/examples/test-examples/ApplicationLayoutNoTopNav.example';
import RoutingMenu from './packages/terra-application-layout/examples/test-examples/RoutingMenu.example';
import RoutingMenuNoHeader from './packages/terra-application-layout/examples/test-examples/RoutingMenuNoHeader.example';
import ApplicationTabsCenter from './packages/terra-application-links/examples/test-examples/ApplicationTabsCenter.example';
import ApplicationTabsDefault from './packages/terra-application-links/examples/test-examples/ApplicationTabsDefault.example';
import ApplicationTabsEnd from './packages/terra-application-links/examples/test-examples/ApplicationTabsEnd.example';
import ApplicationTabsStart from './packages/terra-application-links/examples/test-examples/ApplicationTabsStart.example';
import ApplicationMenuDefault from './packages/terra-application-menu-layout/examples/test-examples/ApplicationMenuDefault.example';
import ApplicationHeaderNameDefault from './packages/terra-application-name/examples/test-examples/ApplicationHeaderNameDefault.example';
import ApplicationHeaderNameTruncated from './packages/terra-application-name/examples/test-examples/ApplicationHeaderNameTruncated.example';
import ApplicationMenuNameDefault from './packages/terra-application-name/examples/test-examples/ApplicationMenuNameDefault.example';
import ApplicationMenuNameTruncated from './packages/terra-application-name/examples/test-examples/ApplicationMenuNameTruncated.example';
import DefaultApplicationHeaderUtility from './packages/terra-application-utility/examples/test-examples/DefaultApplicationHeaderUtility.example';
import DefaultApplicationMenuUtility from './packages/terra-application-utility/examples/test-examples/DefaultApplicationMenuUtility.example';
import DefaultHeaderUtilityMenu from './packages/terra-application-utility/examples/test-examples/DefaultHeaderUtilityMenu.example';
import DefaultMenuUtilityMenu from './packages/terra-application-utility/examples/test-examples/DefaultMenuUtilityMenu.example';
import DefaultHookshot from './packages/terra-hookshot/examples/test-examples/DefaultHookshot.example';
import HookshotAttachmentBehaviorAuto from './packages/terra-hookshot/examples/test-examples/HookshotAttachmentBehaviorAuto.example';
import HookshotAttachmentBehaviorFlip from './packages/terra-hookshot/examples/test-examples/HookshotAttachmentBehaviorFlip.example';
import HookshotAttachmentBehaviorNone from './packages/terra-hookshot/examples/test-examples/HookshotAttachmentBehaviorNone.example';
import HookshotAttachmentBehaviorPush from './packages/terra-hookshot/examples/test-examples/HookshotAttachmentBehaviorPush.example';
import HookshotAttachmentMargin from './packages/terra-hookshot/examples/test-examples/HookshotAttachmentMargin.example';
import HookshotBoundingContainer from './packages/terra-hookshot/examples/test-examples/HookshotBoundingContainer.example';
import HookshotCloseBehaviors from './packages/terra-hookshot/examples/test-examples/HookshotCloseBehaviors.example';
import HookshotContentAttachmentBC from './packages/terra-hookshot/examples/test-examples/HookshotContentAttachmentBC.example';
import HookshotContentAttachmentBE from './packages/terra-hookshot/examples/test-examples/HookshotContentAttachmentBE.example';
import HookshotContentAttachmentBS from './packages/terra-hookshot/examples/test-examples/HookshotContentAttachmentBS.example';
import HookshotContentAttachmentMC from './packages/terra-hookshot/examples/test-examples/HookshotContentAttachmentMC.example';
import HookshotContentAttachmentME from './packages/terra-hookshot/examples/test-examples/HookshotContentAttachmentME.example';
import HookshotContentAttachmentMS from './packages/terra-hookshot/examples/test-examples/HookshotContentAttachmentMS.example';
import HookshotContentAttachmentTC from './packages/terra-hookshot/examples/test-examples/HookshotContentAttachmentTC.example';
import HookshotContentAttachmentTE from './packages/terra-hookshot/examples/test-examples/HookshotContentAttachmentTE.example';
import HookshotContentAttachmentTS from './packages/terra-hookshot/examples/test-examples/HookshotContentAttachmentTS.example';
import HookshotContentOffset from './packages/terra-hookshot/examples/test-examples/HookshotContentOffset.example';
import HookshotEnabledBehaviors from './packages/terra-hookshot/examples/test-examples/HookshotEnabledBehaviors.example';
import HookshotTargetOffset from './packages/terra-hookshot/examples/test-examples/HookshotTargetOffset.example';
import InfiniteListLoading from './packages/terra-infinite-list/examples/test-examples/InfiniteListLoading.example';
import InfiniteListSelection from './packages/terra-infinite-list/examples/test-examples/InfiniteListSelection.example';
import InfiniteListUpdating from './packages/terra-infinite-list/examples/test-examples/InfiniteListUpdating.example';
import InfiniteListVirtual from './packages/terra-infinite-list/examples/test-examples/InfiniteListVirtual.example';
import LayoutDefault from './packages/terra-layout/examples/test-examples/LayoutDefault.example';
import LayoutNoHeader from './packages/terra-layout/examples/test-examples/LayoutNoHeader.example';
import LayoutNoMenu from './packages/terra-layout/examples/test-examples/LayoutNoMenu.example';
import LayoutSlidePanelExample from './packages/terra-layout/examples/test-examples/LayoutSlidePanelExample.example';
import ModalManagerDefault from './packages/terra-modal-manager/examples/test-examples/ModalManagerDefault.example';
import NavigationLayoutBasic from './packages/terra-navigation-layout/examples/test-examples/NavigationLayoutBasic.example';
import NavigationLayoutComplex from './packages/terra-navigation-layout/examples/test-examples/NavigationLayoutComplex.example';
import NavigationSideMenuDefault from './packages/terra-navigation-side-menu/examples/test-examples/NavigationSideMenuDefault.example';
import NavigationSideMenuRoot from './packages/terra-navigation-side-menu/examples/test-examples/NavigationSideMenuRoot.example';
import ArrowHorizontalAttachmentsPopup from './packages/terra-popup/examples/test-examples/ArrowHorizontalAttachmentsPopup.example';
import ArrowHorizontalTargetPopup from './packages/terra-popup/examples/test-examples/ArrowHorizontalTargetPopup.example';
import ArrowPopup from './packages/terra-popup/examples/test-examples/ArrowPopup.example';
import ArrowPopupClosed from './packages/terra-popup/examples/test-examples/ArrowPopupClosed.example';
import ArrowSmallTargetLeftPopup from './packages/terra-popup/examples/test-examples/ArrowSmallTargetLeftPopup.example';
import ArrowSmallTargetRightPopup from './packages/terra-popup/examples/test-examples/ArrowSmallTargetRightPopup.example';
import ArrowVerticalAttachmentsPopup from './packages/terra-popup/examples/test-examples/ArrowVerticalAttachmentsPopup.example';
import ArrowVerticalLeftAdjustmentPopup from './packages/terra-popup/examples/test-examples/ArrowVerticalLeftAdjustmentPopup.example';
import ArrowVerticalRightAdjustmentPopup from './packages/terra-popup/examples/test-examples/ArrowVerticalRightAdjustmentPopup.example';
import AutomaticHeightBoundedPopup from './packages/terra-popup/examples/test-examples/AutomaticHeightBoundedPopup.example';
import AutomaticHeightPopup from './packages/terra-popup/examples/test-examples/AutomaticHeightPopup.example';
import AutomaticWidthBoundedPopup from './packages/terra-popup/examples/test-examples/AutomaticWidthBoundedPopup.example';
import AutomaticWidthPopup from './packages/terra-popup/examples/test-examples/AutomaticWidthPopup.example';
import BoundedHeightPopup from './packages/terra-popup/examples/test-examples/BoundedHeightPopup.example';
import BoundedPopup from './packages/terra-popup/examples/test-examples/BoundedPopup.example';
import BoundedPopupClosed from './packages/terra-popup/examples/test-examples/BoundedPopupClosed.example';
import BoundedWidthPopup from './packages/terra-popup/examples/test-examples/BoundedWidthPopup.example';
import ClassNamePopup from './packages/terra-popup/examples/test-examples/ClassNamePopup.example';
import DefaultPopup from './packages/terra-popup/examples/test-examples/DefaultPopup.example';
import DifferentAttachmentsPopup from './packages/terra-popup/examples/test-examples/DifferentAttachmentsPopup.example';
import NoHeaderPopup from './packages/terra-popup/examples/test-examples/NoHeaderPopup.example';
import OverlayPopup from './packages/terra-popup/examples/test-examples/OverlayPopup.example';
import PopupInsideModal from './packages/terra-popup/examples/test-examples/PopupInsideModal.example';
import ResizedContentPopup from './packages/terra-popup/examples/test-examples/ResizedContentPopup.example';
import SizeInvalidPopup from './packages/terra-popup/examples/test-examples/SizeInvalidPopup.example';
import SizeLargePopup from './packages/terra-popup/examples/test-examples/SizeLargePopup.example';
import SizeMediumPopup from './packages/terra-popup/examples/test-examples/SizeMediumPopup.example';
import SizeSmallPopup from './packages/terra-popup/examples/test-examples/SizeSmallPopup.example';
import SlidePanelManagerDefault from './packages/terra-slide-panel-manager/examples/test-examples/SlidePanelManagerDefault.example';
import SlidePanelEnd from './packages/terra-slide-panel/examples/test-examples/SlidePanelEnd.example';
import SlidePanelFill from './packages/terra-slide-panel/examples/test-examples/SlidePanelFill.example';
import SlidePanelFullscreen from './packages/terra-slide-panel/examples/test-examples/SlidePanelFullscreen.example';
import SlidePanelLarge from './packages/terra-slide-panel/examples/test-examples/SlidePanelLarge.example';
import SlidePanelNoFill from './packages/terra-slide-panel/examples/test-examples/SlidePanelNoFill.example';
import SlidePanelOverlay from './packages/terra-slide-panel/examples/test-examples/SlidePanelOverlay.example';
import SlidePanelSmall from './packages/terra-slide-panel/examples/test-examples/SlidePanelSmall.example';
import SlidePanelSquish from './packages/terra-slide-panel/examples/test-examples/SlidePanelSquish.example';
import SlidePanelSquishLarge from './packages/terra-slide-panel/examples/test-examples/SlidePanelSquishLarge.example';
import SlidePanelStart from './packages/terra-slide-panel/examples/test-examples/SlidePanelStart.example';
import SlidePanelToggle from './packages/terra-slide-panel/examples/test-examples/SlidePanelToggle.example';
import DefaultThemeProvider from './packages/terra-theme-provider/examples/test-examples/DefaultThemeProvider.example';
import GlobalSwitchThemes from './packages/terra-theme-provider/examples/test-examples/GlobalSwitchThemes.example';
import GlobalThemeProvider from './packages/terra-theme-provider/examples/test-examples/GlobalThemeProvider.example';
import SwitchThemes from './packages/terra-theme-provider/examples/test-examples/SwitchThemes.example';
import ThemeProviderNoTheme from './packages/terra-theme-provider/examples/test-examples/ThemeProviderNoTheme.example';

const componentConfig = {
  'terra-aggregator': {
    name: 'Aggregator',
    path: '/aggregator',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraAggregatorIndex,
      },
    ],
    tests: [
      {
        name: 'Aggregator Standalone',
        path: '/aggregator-standalone',
        component: AggregatorStandalone,
      },
      {
        name: 'Aggregator With Disclosure',
        path: '/aggregator-with-disclosure',
        component: AggregatorWithDisclosure,
      },
    ],
  },
  'terra-app-delegate': {
    name: 'App Delegate',
    path: '/app-delegate',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraAppDelegateIndex,
      },
    ],
  },
  'terra-application-header-layout': {
    name: 'Application Header Layout',
    path: '/application-header-layout',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraApplicationHeaderLayoutIndex,
      },
    ],
    tests: [
      {
        name: 'Application Header Default',
        path: '/application-header-default',
        component: ApplicationHeaderDefault,
      },
    ],
  },
  'terra-application-layout': {
    name: 'Application Layout',
    path: '/application-layout',
    pages: [
      {
        name: 'About',
        path: '/about',
        component: TerraApplicationLayoutAbout,
      },
      {
        name: 'Example',
        path: '/example',
        component: TerraApplicationLayoutExample,
      },
      {
        name: 'Utils',
        path: '/utils',
        component: TerraApplicationLayoutUtils,
      },
    ],
    tests: [
      {
        name: 'Application Layout',
        path: '/application-layout',
        component: ApplicationLayout,
      },
      {
        name: 'Application Layout Empty',
        path: '/application-layout-empty',
        component: ApplicationLayoutEmpty,
      },
      {
        name: 'Application Layout Header',
        path: '/application-layout-header',
        component: ApplicationLayoutHeader,
      },
      {
        name: 'Application Layout Header Small',
        path: '/application-layout-header-small',
        component: ApplicationLayoutHeaderSmall,
      },
      {
        name: 'Application Layout Menu',
        path: '/application-layout-menu',
        component: ApplicationLayoutMenu,
      },
      {
        name: 'Application Layout No Top Nav',
        path: '/application-layout-no-top-nav',
        component: ApplicationLayoutNoTopNav,
      },
      {
        name: 'Routing Menu',
        path: '/routing-menu',
        component: RoutingMenu,
      },
      {
        name: 'Routing Menu No Header',
        path: '/routing-menu-no-header',
        component: RoutingMenuNoHeader,
      },
    ],
  },
  'terra-application-links': {
    name: 'Application Links',
    path: '/application-links',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraApplicationLinksIndex,
      },
    ],
    tests: [
      {
        name: 'Application Tabs Center',
        path: '/application-tabs-center',
        component: ApplicationTabsCenter,
      },
      {
        name: 'Application Tabs Default',
        path: '/application-tabs-default',
        component: ApplicationTabsDefault,
      },
      {
        name: 'Application Tabs End',
        path: '/application-tabs-end',
        component: ApplicationTabsEnd,
      },
      {
        name: 'Application Tabs Start',
        path: '/application-tabs-start',
        component: ApplicationTabsStart,
      },
    ],
  },
  'terra-application-menu-layout': {
    name: 'Application Menu Layout',
    path: '/application-menu-layout',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraApplicationMenuLayoutIndex,
      },
    ],
    tests: [
      {
        name: 'Application Menu Default',
        path: '/application-menu-default',
        component: ApplicationMenuDefault,
      },
    ],
  },
  'terra-application-name': {
    name: 'Application Name',
    path: '/application-name',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraApplicationNameIndex,
      },
    ],
    tests: [
      {
        name: 'Application Header Name Default',
        path: '/application-header-name-default',
        component: ApplicationHeaderNameDefault,
      },
      {
        name: 'Application Header Name Truncated',
        path: '/application-header-name-truncated',
        component: ApplicationHeaderNameTruncated,
      },
      {
        name: 'Application Menu Name Default',
        path: '/application-menu-name-default',
        component: ApplicationMenuNameDefault,
      },
      {
        name: 'Application Menu Name Truncated',
        path: '/application-menu-name-truncated',
        component: ApplicationMenuNameTruncated,
      },
    ],
  },
  'terra-application-utility': {
    name: 'Application Utility',
    path: '/application-utility',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraApplicationUtilityIndex,
      },
    ],
    tests: [
      {
        name: 'Default Application Header Utility',
        path: '/default-application-header-utility',
        component: DefaultApplicationHeaderUtility,
      },
      {
        name: 'Default Application Menu Utility',
        path: '/default-application-menu-utility',
        component: DefaultApplicationMenuUtility,
      },
      {
        name: 'Default Header Utility Menu',
        path: '/default-header-utility-menu',
        component: DefaultHeaderUtilityMenu,
      },
      {
        name: 'Default Menu Utility Menu',
        path: '/default-menu-utility-menu',
        component: DefaultMenuUtilityMenu,
      },
    ],
  },
  'terra-disclosure-manager': {
    name: 'Disclosure Manager',
    path: '/disclosure-manager',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraDisclosureManagerIndex,
      },
    ],
  },
  'terra-hookshot': {
    name: 'Hookshot',
    path: '/hookshot',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraHookshotIndex,
      },
    ],
    tests: [
      {
        name: 'Default Hookshot',
        path: '/default-hookshot',
        component: DefaultHookshot,
      },
      {
        name: 'Hookshot Attachment Behavior Auto',
        path: '/hookshot-attachment-behavior-auto',
        component: HookshotAttachmentBehaviorAuto,
      },
      {
        name: 'Hookshot Attachment Behavior Flip',
        path: '/hookshot-attachment-behavior-flip',
        component: HookshotAttachmentBehaviorFlip,
      },
      {
        name: 'Hookshot Attachment Behavior None',
        path: '/hookshot-attachment-behavior-none',
        component: HookshotAttachmentBehaviorNone,
      },
      {
        name: 'Hookshot Attachment Behavior Push',
        path: '/hookshot-attachment-behavior-push',
        component: HookshotAttachmentBehaviorPush,
      },
      {
        name: 'Hookshot Attachment Margin',
        path: '/hookshot-attachment-margin',
        component: HookshotAttachmentMargin,
      },
      {
        name: 'Hookshot Bounding Container',
        path: '/hookshot-bounding-container',
        component: HookshotBoundingContainer,
      },
      {
        name: 'Hookshot Close Behaviors',
        path: '/hookshot-close-behaviors',
        component: HookshotCloseBehaviors,
      },
      {
        name: 'Hookshot Content Attachment BC',
        path: '/hookshot-content-attachment-bc',
        component: HookshotContentAttachmentBC,
      },
      {
        name: 'Hookshot Content Attachment BE',
        path: '/hookshot-content-attachment-be',
        component: HookshotContentAttachmentBE,
      },
      {
        name: 'Hookshot Content Attachment BS',
        path: '/hookshot-content-attachment-bs',
        component: HookshotContentAttachmentBS,
      },
      {
        name: 'Hookshot Content Attachment MC',
        path: '/hookshot-content-attachment-mc',
        component: HookshotContentAttachmentMC,
      },
      {
        name: 'Hookshot Content Attachment ME',
        path: '/hookshot-content-attachment-me',
        component: HookshotContentAttachmentME,
      },
      {
        name: 'Hookshot Content Attachment MS',
        path: '/hookshot-content-attachment-ms',
        component: HookshotContentAttachmentMS,
      },
      {
        name: 'Hookshot Content Attachment TC',
        path: '/hookshot-content-attachment-tc',
        component: HookshotContentAttachmentTC,
      },
      {
        name: 'Hookshot Content Attachment TE',
        path: '/hookshot-content-attachment-te',
        component: HookshotContentAttachmentTE,
      },
      {
        name: 'Hookshot Content Attachment TS',
        path: '/hookshot-content-attachment-ts',
        component: HookshotContentAttachmentTS,
      },
      {
        name: 'Hookshot Content Offset',
        path: '/hookshot-content-offset',
        component: HookshotContentOffset,
      },
      {
        name: 'Hookshot Enabled Behaviors',
        path: '/hookshot-enabled-behaviors',
        component: HookshotEnabledBehaviors,
      },
      {
        name: 'Hookshot Target Offset',
        path: '/hookshot-target-offset',
        component: HookshotTargetOffset,
      },
    ],
  },
  'terra-infinite-list': {
    name: 'Infinite List',
    path: '/infinite-list',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraInfiniteListIndex,
      },
    ],
    tests: [
      {
        name: 'Infinite List Loading',
        path: '/infinite-list-loading',
        component: InfiniteListLoading,
      },
      {
        name: 'Infinite List Selection',
        path: '/infinite-list-selection',
        component: InfiniteListSelection,
      },
      {
        name: 'Infinite List Updating',
        path: '/infinite-list-updating',
        component: InfiniteListUpdating,
      },
      {
        name: 'Infinite List Virtual',
        path: '/infinite-list-virtual',
        component: InfiniteListVirtual,
      },
    ],
  },
  'terra-layout': {
    name: 'Layout',
    path: '/layout',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraLayoutIndex,
      },
    ],
    tests: [
      {
        name: 'Layout Default',
        path: '/layout-default',
        component: LayoutDefault,
      },
      {
        name: 'Layout No Header',
        path: '/layout-no-header',
        component: LayoutNoHeader,
      },
      {
        name: 'Layout No Menu',
        path: '/layout-no-menu',
        component: LayoutNoMenu,
      },
      {
        name: 'Layout Slide Panel Example',
        path: '/layout-slide-panel-example',
        component: LayoutSlidePanelExample,
      },
    ],
  },
  'terra-modal-manager': {
    name: 'Modal Manager',
    path: '/modal-manager',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraModalManagerIndex,
      },
    ],
    tests: [
      {
        name: 'Modal Manager Default',
        path: '/modal-manager-default',
        component: ModalManagerDefault,
      },
    ],
  },
  'terra-navigation-layout': {
    name: 'Navigation Layout',
    path: '/navigation-layout',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraNavigationLayoutIndex,
      },
    ],
    tests: [
      {
        name: 'Navigation Layout Basic',
        path: '/navigation-layout-basic',
        component: NavigationLayoutBasic,
      },
      {
        name: 'Navigation Layout Complex',
        path: '/navigation-layout-complex',
        component: NavigationLayoutComplex,
      },
    ],
  },
  'terra-navigation-side-menu': {
    name: 'Navigation Side Menu',
    path: '/navigation-side-menu',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraNavigationSideMenuIndex,
      },
    ],
    tests: [
      {
        name: 'Navigation Side Menu Default',
        path: '/navigation-side-menu-default',
        component: NavigationSideMenuDefault,
      },
      {
        name: 'Navigation Side Menu Root',
        path: '/navigation-side-menu-root',
        component: NavigationSideMenuRoot,
      },
    ],
  },
  'terra-popup': {
    name: 'Popup',
    path: '/popup',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraPopupIndex,
      },
    ],
    tests: [
      {
        name: 'Arrow Horizontal Attachments Popup',
        path: '/arrow-horizontal-attachments-popup',
        component: ArrowHorizontalAttachmentsPopup,
      },
      {
        name: 'Arrow Horizontal Target Popup',
        path: '/arrow-horizontal-target-popup',
        component: ArrowHorizontalTargetPopup,
      },
      {
        name: 'Arrow Popup',
        path: '/arrow-popup',
        component: ArrowPopup,
      },
      {
        name: 'Arrow Popup Closed',
        path: '/arrow-popup-closed',
        component: ArrowPopupClosed,
      },
      {
        name: 'Arrow Small Target Left Popup',
        path: '/arrow-small-target-left-popup',
        component: ArrowSmallTargetLeftPopup,
      },
      {
        name: 'Arrow Small Target Right Popup',
        path: '/arrow-small-target-right-popup',
        component: ArrowSmallTargetRightPopup,
      },
      {
        name: 'Arrow Vertical Attachments Popup',
        path: '/arrow-vertical-attachments-popup',
        component: ArrowVerticalAttachmentsPopup,
      },
      {
        name: 'Arrow Vertical Left Adjustment Popup',
        path: '/arrow-vertical-left-adjustment-popup',
        component: ArrowVerticalLeftAdjustmentPopup,
      },
      {
        name: 'Arrow Vertical Right Adjustment Popup',
        path: '/arrow-vertical-right-adjustment-popup',
        component: ArrowVerticalRightAdjustmentPopup,
      },
      {
        name: 'Automatic Height Bounded Popup',
        path: '/automatic-height-bounded-popup',
        component: AutomaticHeightBoundedPopup,
      },
      {
        name: 'Automatic Height Popup',
        path: '/automatic-height-popup',
        component: AutomaticHeightPopup,
      },
      {
        name: 'Automatic Width Bounded Popup',
        path: '/automatic-width-bounded-popup',
        component: AutomaticWidthBoundedPopup,
      },
      {
        name: 'Automatic Width Popup',
        path: '/automatic-width-popup',
        component: AutomaticWidthPopup,
      },
      {
        name: 'Bounded Height Popup',
        path: '/bounded-height-popup',
        component: BoundedHeightPopup,
      },
      {
        name: 'Bounded Popup',
        path: '/bounded-popup',
        component: BoundedPopup,
      },
      {
        name: 'Bounded Popup Closed',
        path: '/bounded-popup-closed',
        component: BoundedPopupClosed,
      },
      {
        name: 'Bounded Width Popup',
        path: '/bounded-width-popup',
        component: BoundedWidthPopup,
      },
      {
        name: 'Class Name Popup',
        path: '/class-name-popup',
        component: ClassNamePopup,
      },
      {
        name: 'Default Popup',
        path: '/default-popup',
        component: DefaultPopup,
      },
      {
        name: 'Different Attachments Popup',
        path: '/different-attachments-popup',
        component: DifferentAttachmentsPopup,
      },
      {
        name: 'No Header Popup',
        path: '/no-header-popup',
        component: NoHeaderPopup,
      },
      {
        name: 'Overlay Popup',
        path: '/overlay-popup',
        component: OverlayPopup,
      },
      {
        name: 'Popup Inside Modal',
        path: '/popup-inside-modal',
        component: PopupInsideModal,
      },
      {
        name: 'Resized Content Popup',
        path: '/resized-content-popup',
        component: ResizedContentPopup,
      },
      {
        name: 'Size Invalid Popup',
        path: '/size-invalid-popup',
        component: SizeInvalidPopup,
      },
      {
        name: 'Size Large Popup',
        path: '/size-large-popup',
        component: SizeLargePopup,
      },
      {
        name: 'Size Medium Popup',
        path: '/size-medium-popup',
        component: SizeMediumPopup,
      },
      {
        name: 'Size Small Popup',
        path: '/size-small-popup',
        component: SizeSmallPopup,
      },
    ],
  },
  'terra-slide-panel-manager': {
    name: 'Slide Panel Manager',
    path: '/slide-panel-manager',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraSlidePanelManagerIndex,
      },
    ],
    tests: [
      {
        name: 'Slide Panel Manager Default',
        path: '/slide-panel-manager-default',
        component: SlidePanelManagerDefault,
      },
    ],
  },
  'terra-slide-panel': {
    name: 'Slide Panel',
    path: '/slide-panel',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraSlidePanelIndex,
      },
    ],
    tests: [
      {
        name: 'Slide Panel End',
        path: '/slide-panel-end',
        component: SlidePanelEnd,
      },
      {
        name: 'Slide Panel Fill',
        path: '/slide-panel-fill',
        component: SlidePanelFill,
      },
      {
        name: 'Slide Panel Fullscreen',
        path: '/slide-panel-fullscreen',
        component: SlidePanelFullscreen,
      },
      {
        name: 'Slide Panel Large',
        path: '/slide-panel-large',
        component: SlidePanelLarge,
      },
      {
        name: 'Slide Panel No Fill',
        path: '/slide-panel-no-fill',
        component: SlidePanelNoFill,
      },
      {
        name: 'Slide Panel Overlay',
        path: '/slide-panel-overlay',
        component: SlidePanelOverlay,
      },
      {
        name: 'Slide Panel Small',
        path: '/slide-panel-small',
        component: SlidePanelSmall,
      },
      {
        name: 'Slide Panel Squish',
        path: '/slide-panel-squish',
        component: SlidePanelSquish,
      },
      {
        name: 'Slide Panel Squish Large',
        path: '/slide-panel-squish-large',
        component: SlidePanelSquishLarge,
      },
      {
        name: 'Slide Panel Start',
        path: '/slide-panel-start',
        component: SlidePanelStart,
      },
      {
        name: 'Slide Panel Toggle',
        path: '/slide-panel-toggle',
        component: SlidePanelToggle,
      },
    ],
  },
  'terra-theme-provider': {
    name: 'Theme Provider',
    path: '/theme-provider',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraThemeProviderIndex,
      },
    ],
    tests: [
      {
        name: 'Default Theme Provider',
        path: '/default-theme-provider',
        component: DefaultThemeProvider,
      },
      {
        name: 'Global Switch Themes',
        path: '/global-switch-themes',
        component: GlobalSwitchThemes,
      },
      {
        name: 'Global Theme Provider',
        path: '/global-theme-provider',
        component: GlobalThemeProvider,
      },
      {
        name: 'Switch Themes',
        path: '/switch-themes',
        component: SwitchThemes,
      },
      {
        name: 'Theme Provider No Theme',
        path: '/theme-provider-no-theme',
        component: ThemeProviderNoTheme,
      },
    ],
  },
};

export default componentConfig;
